name: ioSPI
channels:
  - conda-forge
  - defaults
dependencies:
  - codecov
  - coverage
  - gemmi
  - mrcfile
  - numba
  - numpy
  - h5py>=2.10.0
  - pillow>=8.2.0
  - pip
  - pyfftw
  - pytest
  - pytest-cov
  - pytorch
  - pyyaml
  - pip:
    - git+https://github.com/compSPI/simSPI.git

